### ISSUE TITLE
`lsprotocol` is too strict when parsing `CodeActionKind`?

### ISSUE THREAD

**Issue by alcarney** [microsoft/lsprotocol#101]
During the process of aligning [pytest-lsp](https://github.com/alcarney/lsp-devtools/tree/develop/lib/pytest-lsp) to the `1.0` branch in `pygls` I've noticed that `lsprotocol` refuses to parse the client capabilities reported by any (currently released) version of neovim.

Specifically, when parsing the `codeActionLiteralSupport` field of `CodeActionClientCapabilities`
```json
"codeActionLiteralSupport": {
  "codeActionKind": {
    "valueSet": [
      "",
      "Empty",
      "QuickFix",
      "Refactor",
      "RefactorExtract",
      "RefactorInline",
      "RefactorRewrite",
      "Source",
      "SourceOrganizeImports",
      "quickfix",
      "refactor",
      "refactor.extract",
      "refactor.inline",
      "refactor.rewrite",
      "source",
      "source.organizeImports"
    ]
  }
}
```
While the extra values are due to a bug (neovim/neovim#20678) that is now fixed upstream, until the fix is available in a released version anyone using neovim will not be able to use a `pygls v1.0` powered language server.

Looking at the spec the set of `CodeActionKinds` is "open" so I'm wondering if the type definition for the `valueSet` field should be relaxed from `List[CodeActionKind]` to `List[str]`?
```
/**
 * The kind of a code action.
 *
 * Kinds are a hierarchical list of identifiers separated by `.`,
 * e.g. `"refactor.extract.function"`.
 *
 * The set of kinds is open and client needs to announce the kinds it supports
 * to the server during initialization.
 */
export type CodeActionKind = string;

/**
 * A set of predefined code action kinds.
 */
export namespace CodeActionKind {
  ...
}
```

I'm also wondering if you have any thoughts more generally on how a server could opt in to be more forgiving on the input it accepts?

**Comment by karthiknadig** [comment]
@dbaeumer is there a field in LSP model that says that something can be "open" ? so we can relax the validation on those properties?

**Comment by dbaeumer** [comment]
Yes, enums that can have custom values have a property `supportsCustomValues` set to `true`.
