### ISSUE TITLE
Reading full context

### ISSUE THREAD

**Issue by djtech-dev** [microsoft/lsprotocol#221]
Hi, I wanted to ask how to read the full context (like the actual line of code or the lines of code previous to the current buffer) from `CompletionParams`.

Thanks.

**Comment by karthiknadig** [comment]
You will need to use Document Synchronization to have the document on server side synced with the document on the client side: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_synchronization

This library only provides the types that are needed for the protocol. If you want base server to implement your server on top of you should use `pygls` which provides a lot of convenience features out of the box (https://pypi.org/project/pygls/) .

Here is an implementation of Completion request using `CompletionParams`:
https://github.com/pappasam/jedi-language-server/blob/6b064bca61a3e56535c27cc8c8b20f45a3fcbe47/jedi_language_server/server.py#L189
