### ISSUE TITLE
`PositionEncodingKind` hook

### ISSUE THREAD

**Issue by tombh** [microsoft/lsprotocol#270]
Does this `cattrs` hook need to be added?
```python
converter.register_structure_hook(
    Union[PositionEncodingKind, str, None], lambda obj, _: obj
)
```

I'm adding support for LSP 3.17's position encoding negotiation in Pygls and I was getting errors during server initialisation. The PR is here https://github.com/openlawlibrary/pygls/pull/375

It's the first time I've come across this area of the codebase, so I'm not completely clear about what the best solution is.

**Comment by karthiknadig** [comment]
Yes, this likely needs a hook. It should go in this file:
https://github.com/microsoft/lsprotocol/blob/main/packages/python/lsprotocol/_hooks.py

Example hook here:
Hook def: https://github.com/microsoft/lsprotocol/blob/main/packages/python/lsprotocol/_hooks.py#L194-L201
Add it here: https://github.com/microsoft/lsprotocol/blob/main/packages/python/lsprotocol/_hooks.py#L703-L706

I will add this tomorrow.

**Comment by karthiknadig** [comment]
I have added a new test suite that should catch all these issues.
https://github.com/microsoft/lsprotocol/pull/273

it adds significantly more coverage:
![image](https://github.com/microsoft/lsprotocol/assets/3840081/33240534-ceb6-4cbd-bede-9c5a1b32fa59)
