### ISSUE TITLE
return types to the client

### ISSUE THREAD

**Issue by barkanido** [microsoft/lsprotocol#278]
Hi,
I am using `pygls` to write a vscode extension, and I wonder what types of "raw" data can be returned from the server to the client. For example, can I return Python strings or nested datatypes, or should I wrap them in the LSP protocol types?

**Comment by karthiknadig** [comment]
If you are creating custom messages, then you can return anything that can be serialized. For specific request or response that is part of LSP, then in some cases it will allow you to return custom values. But remember, what ever you return it should have the structure of a Response message: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage
