### ISSUE TITLE
Regression introduced by `cattrs v23.2.1` with `Any | None`

### ISSUE THREAD

**Issue by jhossbach** [microsoft/lsprotocol#301]
Takeaway from https://github.com/python-lsp/python-lsp-ruff/issues/61:
 > I managed to track it down. There's a type in `lsprotocol.types`, `LSPAny`, typed as `Union[Any, None]`.
Looks like there's a regression in unstructuring this type, it used to be unstructured as the runtime type, and now is unstructured as `Any`.

_Originally posted by @Tinche in https://github.com/python-lsp/python-lsp-ruff/issues/61#issuecomment-1818933283_
            
The issue is solved with `cattrs>=23.2.2`. Can we make the `cattrs` dependency more strict?

**Comment by karthiknadig** [comment]
@jhossbach Feel free to provide the PR.
Add it in these two places:
https://github.com/microsoft/lsprotocol/blob/main/requirements.in : This is used for CI/CD and local development
https://github.com/microsoft/lsprotocol/blob/main/packages/python/pyproject.toml : This is the actual package deps

**Comment by jhossbach** [comment]
Gladly, just a question: Do I also need to touch [`packages/python/requirements.in`](https://github.com/microsoft/lsprotocol/blob/main/packages/python/requirements.in)?

**Comment by karthiknadig** [comment]
Nope, I plan on removing those as we have the dependencies described now in `pyproject.toml`
