### ISSUE TITLE
Publish new version with support for LSP 3.18

### ISSUE THREAD

**Issue by rowillia** [microsoft/lsprotocol#369]
Hi all,

Do mind publishing a new release to pypi w/ support for LSP 3.18?  I see you recently updated `main` for 3.18 and I'd love to try some of the new features like `SnippetTextEdit`.

Thanks!

**Comment by karthiknadig** [comment]
Yes we will publish soon. Doing some internal testing.

**Comment by rowillia** [comment]
Great to hear @karthiknadig !  

When trying to move to migrate pygls to the latest version I noticed there have been a lot of breakages since the package was last published (e.g. `WorkspaceConfigurationParams` => `ConfigurationParams`, `TraceValues` => `TraceValue`, `TextDocumentContentChangeEvent_Type1` => `TextDocumentContentChangePartial`).

Is there way to have a compatibility shim to make the update easier?  Are the set of changes documented anywhere?

Since `pygls` [depends on the `lsprotocol`](https://pygls.readthedocs.io/en/v1.0.1/pages/migrating-to-v1.html) types this would also require changes to all existing extensions (several of which [were written](https://github.com/openlawlibrary/pygls/blob/main/Implementations.md) by Microsfot)

**Comment by karthiknadig** [comment]
Published a pre-release version with new LSP 3.18. I also updated `pygls` see here: https://github.com/openlawlibrary/pygls/pull/487

They are both pinned to specific versions, and I plan to update Microsoft extensions to use the new pygls once it has a stable release.
