### ISSUE TITLE
How do you check whether a client supports `workspace/didChangeWorkspaceFolders`?

### ISSUE THREAD

**Issue by bzoracler** [microsoft/lsprotocol#391]
With the [`lsprotocol.types.WorkspaceClientCapabilities`](https://github.com/microsoft/lsprotocol/blob/7c38dfe4c5da572b1b258ba08dda3291e8fcd838/packages/python/lsprotocol/types.py#L7165) object, I understand that you can check other client capabilities like

* `workspace/configuration`
* `workspace/didChangeConfiguration`
* `workspace/workspaceFolders`

However, there is no corresponding field for `workspace/didChangeWorkspaceFolders`. How do you determine whether a client supports this capability?

A more general question - why is this field missing from the `WorkspaceClientCapabilities`?

**Comment by karthiknadig** [comment]
This should be filed on the LSP spec here ( https://github.com/microsoft/vscode-languageserver-node/issues ). This repo is for implementations based on the LSP spec model (https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/metaModel.json). Any changes to types or new fields go into the model there.

For `workspace/didChangeConfiguration`, the spec defines it like this:
```
        {
            "method": "workspace/didChangeConfiguration",
            "typeName": "DidChangeConfigurationNotification",
            "messageDirection": "clientToServer",
            "params": {
                "kind": "reference",
                "name": "DidChangeConfigurationParams"
            },
            "registrationOptions": {
                "kind": "reference",
                "name": "DidChangeConfigurationRegistrationOptions"
            },
            "documentation": "The configuration change notification is sent from the client to the server\nwhen the client's configuration has changed. The notification contains\nthe changed configuration as defined by the language client."
        },
```

For `workspace/didChangeWorkspaceFolders`, the spec defines it like this:
```
        {
            "method": "workspace/didChangeWorkspaceFolders",
            "typeName": "DidChangeWorkspaceFoldersNotification",
            "messageDirection": "clientToServer",
            "params": {
                "kind": "reference",
                "name": "DidChangeWorkspaceFoldersParams"
            },
            "documentation": "The `workspace/didChangeWorkspaceFolders` notification is sent from the client to the server when the workspace\nfolder configuration changes."
        }
```
