### ISSUE TITLE
Support for Crystal Lang

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/lsprotocol#400]
@nobodywasishere I created a feature request here to track (https://github.com/microsoft/lsprotocol/pull/397)

**Comment by karthiknadig** [comment]
Thanks for the feature request! We are going to give the community 4 months from when this issue was created to provide 10 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by karthiknadig** [comment]
Hey @nobodywasishere, we really appreciate the interest in submitting this contribution and we'll leave this issue open. I do want to call out that we're a small team, so accepting the PR would also mean that we'll be in charge of maintaining the code here, and I'm afraid we unfortunately don't have the bandwidth to do that. 
 
However, from a maintainability and shipping point of view, you should be able to use to generator in your own repo to generate code and test your LSP module.

Here is how we set it up to work:
1. Create a python virtual environment: `python -m venv .venv` (use latest python)
2. Activate the environment: 
   * Windows: `.venv\Script\activate`
   * Linux\mac: `source .venv\bin\activate`
3. Install the generator: `python -m pip install git+https://github.com/microsoft/lsprotocol`
4. Run generator with crystal plugin: `python -m generator --plugin crystalgen --output-dir ./package --test-dir ./tests`

![image](https://github.com/user-attachments/assets/3f71e8f4-f25b-4144-8965-e49c4de90d1b)

![image](https://github.com/user-attachments/assets/f451dd4e-9c01-4633-8477-df29fb626732)

![image](https://github.com/user-attachments/assets/1f1c2f87-7bc3-4ea8-80c6-82686458d289)


That should generate the package.  If you end up publishing it, we'd be happy to link to it from our README.

**Comment by karthiknadig** [comment]
@nobodywasishere I can make a PR to the https://github.com/nobodywasishere/lsprotocol-crystal , since I have tried this out locally I have a branch that is working.

**Comment by nobodywasishere** [comment]
Honestly that's completely fair, thank you at least for considering it. I hadn't thought about trying to use the lsprotocol repo as a plugin instead of having everything in-tree, which would honestly work perfectly. Only question I have is how feasible it is to output the contents in the current folder instead of a subdirectory (`/package/lsprotocol` => `.`). But that's something I can figure out. If you want to create a PR I would be happy to review / accept it, and I greatly appreciate your help with this!

**Comment by karthiknadig** [comment]
Here is the PR: https://github.com/nobodywasishere/lsprotocol-crystal/pull/1

This is the command I used to generate it. I also did a few fixes to the `crystalgen`.
command: `python -m generator --plugin crystalgen --output-dir . --test-dir ./tests`

**Comment by karthiknadig** [comment]
Closing this, now that the generator is integrated at https://github.com/nobodywasishere/lsprotocol-crystal
