### ISSUE TITLE
Missing fields in `<MethodName>RegistrationOptions` type definitions

### ISSUE THREAD

**Issue by alcarney** [microsoft/lsprotocol#71]
From what I can tell the [in the spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionRegistrationOptions) `<MethodName>RegistrationOption` types extend the `<MethodName>Option` types, which in turn often [extend types](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionOptions) such as `WorkDoneProgressOptions`. However, the type definitions in `lsprotocol`, say for example, [`CompletionRegistrationOptions`](https://github.com/microsoft/lsprotocol/blob/b545c8107129e3a39e2c9a46b5d9fecbd8262dc3/lsprotocol/types.py#L3406) are missing the fields corresponding with `WorkDoneProgressOptions`

**Comment by karthiknadig** [comment]
@alcarney This is generated from the meta model for the LSP spec so looks like the spec might be missing it: https://github.com/microsoft/vscode-languageserver-node/blob/e3b566dc9e6ae60fa3d6641c3bb480634e4a0ad8/protocol/metaModel.json#L4876-L489

/cc @dbaeumer

**Comment by karthiknadig** [comment]
Actually, looks like the model is right. Looks like the bug in the `lsprotocol` generator. I will look into it.

**Comment by karthiknadig** [comment]
@alcarney https://pypi.org/project/lsprotocol/2022.0.0a4/ has the fix for this issue.
